### ISSUE TITLE
Merge Upstream Pull Requests

### ISSUE THREAD

**Issue by pi0** [moloquent/moloquent#1]
+ Currently Merged :
 - #834 : Cast data before saving it into database and mongoId as Relationships
 - #926 : Filling with Dot-Notation
 - #918 : Aggregate sub-document arrays
 - #948 : Remove dependency on Laravel Application
 - #953 : Convert whereBetween values to UTCDateTime

**Comment by amiri27** [comment]
@pi0 any chance to merge this: https://github.com/jenssegers/laravel-mongodb/pull/953

**Comment by pi0** [comment]
@amiri27 Merged in 27a47c1 :)

**Comment by amiri27** [comment]
Well done guy...

**Comment by pi0** [comment]
Issue closed and moved to new github `projects` section . [HERE](https://github.com/moloquent/moloquent/projects/)
