### ISSUE TITLE
firstOrCreate method implementation

### ISSUE THREAD

**Issue by adolfocuadros** [moloquent/moloquent#24]
They believe that the implementation of a firstOrCreate () method is necessary ??

**Comment by pi0** [comment]
I think it isn't as base class already implemented it :) Do you have any special need of that ?

**Comment by adolfocuadros** [comment]
Create if not find, I think it is a very useful method, it has been repeatedly used in different cases.

**Comment by adolfocuadros** [comment]
other interesting methods are: SAVER Fail (), findOrFail ()

**Comment by mlanin** [comment]
@adolfocuadros Eloquent already supports:

- `firstOrCreate` https://laravel.com/docs/5.3/eloquent#other-creation-methods
- `findOrFail` https://laravel.com/docs/5.3/eloquent#retrieving-single-models

I don't think that it is a good practice to overdo in creating custom methods. Our target is to provide full Eloquent functionality but with Mongodb sauce.
