### ISSUE TITLE
Compatibility with Laravel Passport is broken.

### ISSUE THREAD

**Issue by luemic** [moloquent/moloquent#25]
Hi guys,

I ran into the following issue using passport and moloquent: 

When checking the Toking I got 'unauthorized' response because of an technical error. After some debugging I found that the Token class is inherited from `Illuminate\Database\Eloquent\Model;`. If I change this to `use Moloquent\Eloquent\Model;` it works as expected. Can you introduce an adjusted Token class and override the original one?

Thanks in advance 

Michael

**Comment by pi0** [comment]
@luemic Hello. Passport support is currently available on `dev-master` version only. please check your `composer.json` also you have to add this service provider to `config/app.php`:  (this will magically fix problem) 

```php
Moloquent\Passport\PassportServiceProvider::class,
```

> Read the docs, debug then ;)

**Comment by luemic** [comment]
@pi0 

my composer.json looks as follows:
 `"moloquent/moloquent": "dev-master#3b97861e52833e3d429b2eed0c90e3e81127d620r",`
and composer.lock states:
`"reference": "3b97861e52833e3d429b2eed0c90e3e81127d620"`

My app/config.php álready includes the 

`Moloquent\Passport\PassportServiceProvider::class,`

However when I make a request I got the following exception:

```
[2016-10-13 16:02:39] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function compileSelect() on null in /meetago7/src/admin-api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1581
Stack trace:
#0 /meetago7/src/admin-api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1648): Illuminate\Database\Query\Builder->toSql()
#1 /meetago7/src/admin-api/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1634): Illuminate\Database\Query\Builder->runSelect()
#2 /meetago7/src/admin-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(613): Illuminate\Database\Query\Builder->get(Array)
#3 /meetago7/src/admin-api/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(318): Illuminate\Database\Eloquent\Builder->getModels(
```

**Comment by pi0** [comment]
And .. Another passport class :))   You were right@luemic we will fix that problem soon .

**Comment by luemic** [comment]
Great :) My approach was to copy the token class and made it use moloquent

```
use Moloquent\Eloquent\Model;

class Token extends Model ...
```

and rewrite the original class by 

```
$loader->alias('Laravel\Passport\Token', Token::class);
```

in the ServiceProviderClass. If there's a better way to fix it, let me know.

**Comment by mlanin** [comment]
@pi0 @luemic had the same problem and the same approach :)

But I had to do more:

- First of all I had to overwrite `TokenRepository` and it's method `find`. It uses default key, but searches by 'id' field. So I had to use where construction `Token::where('id', $id)->first();`
- Also overwrite `AccessTokenRepository` so that it's method `persistNewAccessToken` should use `Token` model to save token instead of direct database insert.
- And the last thing is to overwrite `formatScopesForStorage` method again in `AccessTokenRepository` so that it will return array of scopes instead of encoding it to json.

After that tokens start working right. But it is an awful approach. Lots of aliases...

**Comment by pi0** [comment]
@mlanin very thanks. i have tried to reproduce your patches, also rebased classes to latest `passport` versions. i'll appreciate if you check 8432d6a and making a PR if is there anything wrong ..

**Comment by mlanin** [comment]
@pi0 everything is ok except one major point. If you are registering one class as an alias for the second, you can't extend first from the second, because aliasing is made via native `class_alias` method and after it is done, php will no nothing about the second class.
 
That's why you have to rebuild whole class with every property and methods and then make an alias. And that's why it is a bad option. Because if models will rarely change in future, repositories are parts of logic and will be updated sooner or later and we will have to keep an eye on them every time and recreate logic in our aliases.

I made the same way but that's why I haven't made a PR to implement this approach. It isn't optimal. But I don't know another way :(

**Comment by pi0** [comment]
One idea to simulate that classes behavior is some hour *wrapping around an instance of original class* . , Then using magic call and magic properties to pass everything back to original instance except ones we want to slightly change ...

**Comment by mlanin** [comment]
@pi0 you're talking about some kind a decorator, but as I've said you will not be able to use the original class after alias is registered...

First of all, tomorrow I want to push a PR to Passport to fix direct token insert to database. That will help us to get rid of replacing `AccessTokenRepository`. One step further, I hope :)

**Comment by mlanin** [comment]
#28 this PR should fix the issue. But only for dev-master Passport. I hope it will be released soon

**Comment by pi0** [comment]
@mlanin thanks for that!

**Comment by luemic** [comment]
Hi guys,

unfortunatelly we can not get rid of the `AccessTokenRepository`. I get `unauthorized` response due to 

```php
    /**
     * {@inheritdoc}
     */
    public function isAccessTokenRevoked($tokenId)
    {
        return ! $this->database->table('oauth_access_tokens')
                    ->where('id', $tokenId)->where('revoked', 0)->exists();
    }
```

which needs to be replaced by 

```php

    /**
     * {@inheritdoc}
     */
    public function isAccessTokenRevoked($tokenId)
    {
        return ! $this->database->table('oauth_access_tokens')
                    ->where('id', $tokenId)->where('revoked', false)->exists();
    }

```

**Comment by pi0** [comment]
@luemic Would you please explain more about that problem and (possibly) opening a PR for that?

**Comment by luemic** [comment]
@pi0 looks like a type compatibilty issue. Not working for me:

```php
  ->where('revoked', 0)->exists()
```

working for me

```php
->where('revoked', false)->exists()
```

I'll create a PR later this day,

**Comment by amiri27** [comment]
@pi0 any chance to fix this by model casts attribute?

**Comment by pi0** [comment]
@amiri27 Yes it solves issue, but it may just HIDE the real problem! waiting for @luemic's PR

**Comment by mlanin** [comment]
@pi0 @amiri27 Attribute casting can be our only chance. Because otherwise we have to support LOTS of code...

**Comment by luemic** [comment]
I totally agree with the attribute casting and it's already done for the model

```php
 /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'revoked' => 'bool',
    ];
```

Unfortunatelly my case lies in a repository class which accesses the database directly, so an attribute cast wont help us here :(.

**Comment by pi0** [comment]
What about this ?

```php
    /**
     * {@inheritdoc}
     */
    public function isAccessTokenRevoked($tokenId)
    {
        return ! $this->database->table('oauth_access_tokens')
                    ->where('id', $tokenId)->whereIn('revoked', [false,0])->exists();
    }
```

**Comment by mlanin** [comment]
I made a PR https://github.com/laravel/passport/pull/144 to passport that will fix this problem. Hope it will be merged.

**Comment by amiri27** [comment]
Well done @mlanin . They merged your contribution

**Comment by luemic** [comment]
Is working properly.

**Comment by ctf0** [comment]
all of a sudden i started to get 

![5 3 19](https://cloud.githubusercontent.com/assets/7388088/19630191/56a8bd28-9985-11e6-97df-3513579b2025.jpg)

**Comment by ctf0** [comment]
found it, i had to extend Moloquent in the user model instead after the update @pi0 any chance we could add this part to the docs ?
