### ISSUE TITLE
Moloquent Support.php breaks Laravel optimization

### ISSUE THREAD

**Issue by mlanin** [moloquent/moloquent#26]
When you run `php artisan optimize` it creates compiled.php file that contains all of the Laravel basic classes and interfaces, so that using them doesn't require searhing and autoloading the exact file.

Thing is composer autoloads static php files defined in composer packages first. And in your `SupportClasses/Support.php` there is an explicit load of Moloquent model that fires autoloading lots of Laravel's and Moloquent's additional interfaces and classes BEFORE Laravel loads them from `compiled.php`.

And this makes php die with fatal error:

```
PHP Fatal error:  Cannot declare interface Illuminate\Contracts\Support\Arrayable, because the name is already in use in /home/vagrant/project/bootstrap/cache/compiled.php on line 140
```

This problem makes using optimisation impossible!

One more thing. Composer fires `optimize` command from post-install and post-update scripts, so this issue WILL break any project that will install it's packages on production environment (situation  I had today).

**Comment by pi0** [comment]
@mlanin  thanks, we already experienced it but not found the issue. i'll revert that commit for now ...

**Comment by mlanin** [comment]
@pi0 thanks! 2 hours of debug wasn't wasted :)
