### ISSUE TITLE
Class 'Moloquent\Eloquent\Model' not found

### ISSUE THREAD

**Issue by anewage** [moloquent/moloquent#3]
I've been trying to use Moloquent as a service provider, I kept getting errors since I'm using the following paths in my code (config file and Eloquents):
`Moloquent\MongodbServiceProvider::class`
`Moloquent\Auth\PasswordResetServiceProvider::class`
`Moloquent\Eloquent\Model`

**Edit:**
I've changed

- `Moloquent\MongodbServiceProvider::class` to `Jenssegers\Mongodb\MongodbServiceProvider::class` 

- and `Moloquent\Auth\PasswordResetServiceProvider::class` to `Jenssegers\Mongodb\Auth\PasswordResetServiceProvider::class`

- and also `Moloquent\Eloquent\Model` to `Jenssegers\Mongodb\Eloquent\Model`

and everything is normal.

**Comment by pi0** [comment]
Now 9909714  migrates entire namespace to a new psr-4 called `Moloquent` to avoid any conflicts with original namespace when having both packages installed :) Please upgrade to `5.3.0` then change any `use` statement to new namespace  (New versioning stays up to date with laravel releases)

**Comment by amiri27** [comment]
New version is compatible with PSR-4.. Use with confidence..

**Comment by MehmetNuri** [comment]
Please use this method

`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;
use Illuminate\Contracts\Auth\Authenticatable;


class User extends Eloquent implements Authenticatable
{
    use Notifiable,SoftDeletes, AuthenticableTrait;

    protected $collection = 'users';
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
`
