### ISSUE TITLE
PHP Storm autocomplete

### ISSUE THREAD

**Issue by CihanAksoy** [moloquent/moloquent#31]
PHP Storm autocomplete doesn't work. 

MyModel::all() it's fine but MyModel::where('service', bool)->get() doesn't work.

http://prntscr.com/cvebli

**Comment by pi0** [comment]
Please use [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) for your project! it will give you lots of help for autocompletion. More hinting will be added in next releases ;)

**Comment by CihanAksoy** [comment]
i using ide helper :)

**Comment by iceheat** [comment]
You will need to configure laravel-ide-helper to recognise Moloquent as your DB provider. 
if you check `config/ide-helper.php` under extra you will need to change Eloquent Entry to:
```php 
'Eloquent' => array('Moloquent\Eloquent\Builder', 'Moloquent\Query\Builder'),
```
Let me know how it goes with you.
