### ISSUE TITLE
[Question] how to save an item as ObjectId

### ISSUE THREAD

**Issue by ctf0** [moloquent/moloquent#36]
i tried using something like `"ObjectId(\"{$id}\")"` but this saves it as `string`

**Comment by pi0** [comment]
I think @RTLer can help you better on `ObjectIds` :)

**Comment by ctf0** [comment]
am reading https://docs.mongodb.com/v3.2/reference/method/ObjectId/#generate-a-new-objectid ,is there a way to call something like this through moloquent ?

**Comment by RTLer** [comment]
hi
there is an object for some of the mongo types in mongo php driver
in your case `new MongoDB\BSON\ObjectID($identifier);`

**Comment by ctf0** [comment]
@RTLer thanx but i get this
```bash
 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'MongoDB\BSON\ObjectID' not found
```
