### ISSUE TITLE
[Question] how to change/set the type of a field ?

### ISSUE THREAD

**Issue by ctf0** [moloquent/moloquent#37]
am sorry to bother u again but am currently trying to make a query where it searches for a field of `some_name` and change/set its type to something else , is this even possible ?

here is what i have so far
```php
$tables = DB::getMongoDB()->listCollections();

// update the field on each collection
foreach ($tables as $one) {
    $name = $one->getName();
    DB::table($name)->find($field)->set([
       // ...
    ]);
}
```

this is mostly a part of a tool am creating to help migrate data to mongo from mysql as easy as possible, u can check it in here https://github.com/ctf0/MysqlToMongoDb

**Comment by iceheat** [comment]
I cannot test it at the moment, but I would imagine you would need something along the lines of 
```php
foreach ($tables as $one) {
    $name = $one->getName();
    DB::collection($name)->raw()->updateMany([],[
    $rename=>['old_name'=>'new_name']
    ]);
```

Let me know how it works with you.

**Comment by ctf0** [comment]
sweet, i will test it and get back to u, in the meantime could u plz direct me to where i could find more info / tutorial such this ?

**Comment by iceheat** [comment]
I highly doubt that you would find any tutorials to that level of details. I got the information from MongoDB documentation.
[https://docs.mongodb.com/php-library/master/reference/method/MongoDBCollection-updateMany/](https://docs.mongodb.com/php-library/master/reference/method/MongoDBCollection-updateMany/)
[https://docs.mongodb.com/manual/reference/operator/update/rename/](https://docs.mongodb.com/manual/reference/operator/update/rename/)

**Comment by ctf0** [comment]
@iceheat many thanx
