### ISSUE TITLE
Query Builder error

### ISSUE THREAD

**Issue by Xplouder** [moloquent/moloquent#40]
![github_report](https://cloud.githubusercontent.com/assets/2997254/20310642/a64233fc-ab44-11e6-849a-c39d301099e6.png)
I'm using a mixed databases, mysql is the default and mongodb the second.
My only 2 classes looks like this:

**User**: (pretty much a normal model beside the replace of the `use Moloquent\Eloquent\Model`)
```
<?php

namespace App;

use Moloquent\Eloquent\Model as Moloquent;

class User extends Moloquent
{
    protected $connection = 'mysql';
    protected $table = 'users';
    ...
```

**Post**:

```
<?php

namespace App;

use Moloquent\Eloquent\Model as Moloquent;
use Moloquent\Eloquent\HybridRelations;

class Post extends Moloquent
{
    use HybridRelations;
    protected $connection = 'mongodb';
    protected $collection = 'posts';
    ...
```

According with the stacktrace the erro comes from this line:
```$user =  User::where('email', $socialUser->email)->first();```

I'm doing anything wrong?
Let me know if you want to see any other piece of the code.

**Comment by iceheat** [comment]
I believe that your mySQL models i.e. User should be using the `Illuminate\Database\Eloquent\Model` and implementing `Moloquent\Eloquent\HybridRelations`. I don't think you need the trait for your mongo model.

**Comment by Xplouder** [comment]
That way, the error above vanish but another one appear:
![github_report2](https://cloud.githubusercontent.com/assets/2997254/20311690/9cd10ff6-ab48-11e6-862e-f7be6a400797.png)
I believe this error now happens due the lack of `use Moloquent\Eloquent\Model as Moloquent` in `User` model.

**Comment by ctf0** [comment]
on a side not i would highly recommend using either **mysql** or **mongo**, using both is kinda inefficient and could cuz lots of issues down the road

**Comment by iceheat** [comment]
I don't understand why is it passing a HasMany Object to the query. I would suspect that the issue is caused by UserController->feed() or by your relationship definitions.
In terms of using a Hybrid relationship, it can be very beneficial for specific types of projects. but it is double the headache for  database administrators.

**Comment by Xplouder** [comment]
Apparently the bug come from this line:
`return response()->json($union->paginate(15), 200);`
The $union is just a group of `Post` instances. Seems like the error happens when he try to paginate it, because if i remove the `->paginate(15)` it will return just fine.

**Comment by iceheat** [comment]
try dumping $union. I have a feeling that you are getting the relationship object, or a combination of posts and a relationship object. make sure you are retrieving the posts as `$user->posts` as supposed to `$user->posts()`

**Comment by Xplouder** [comment]
```
$publicPosts = DB::table('posts')->where('public', 'yes');
$authenticatedUserPosts = User::find($authenticatedUser->id)->posts();
$privatePostsOfFriends = DB::table('posts')
    ->join('users', 'users.id', '=', 'posts.user_id')
    ->join('friends', 'users.id', '=', 'friends.user_id_1')
    ->where('users.id', '!=', $authenticatedUser->id)
    ->where('posts.public', 'no')
    ->select('posts.*');
$union = $publicPosts->union($privatePostsOfFriends)
    ->union($authenticatedUserPosts)
    ->orderBy('created_at', 'desc');

return response()->json($union->paginate(15), 200);
```

That is the code I'm using to get the $union. Note that i `->select('posts.*');` to avoid the combination of a relationship object that you refer.

**Comment by iceheat** [comment]
This is your culprit `$authenticatedUserPosts = User::find($authenticatedUser->id)->posts();`

**Comment by Xplouder** [comment]
Erm... ok. So what I'm suppose to change then?
Tryed `$authenticatedUserPosts = DB::connection('mongodb')->collection('posts')->where('user_id', $authenticatedUser->id)`; with no success.

**Comment by iceheat** [comment]
`$authenticatedUserPosts = User::find($authenticatedUser->id)->posts();` gets you the relationship object. 
`$authenticatedUserPosts = User::find($authenticatedUser->id)->posts;` (without the brackets) would get you the items behind the relation.

**Comment by Xplouder** [comment]
That was not a solution for me because i needed it as "eloquent object" to do the union, otherwise i had to append arrays, sort and paginate all manually. Anyway, apparently the last code i posted worked fine after `composer dump-autoload && php artisan clear-compiled && php artisan optimize`.
Anyway, thanks for all the help!
