### ISSUE TITLE
Why this package over original?

### ISSUE THREAD

**Issue by ebisbe** [moloquent/moloquent#41]
Hello Guys,
I've been using the original package for almost a year now and recently found that other package. Why I should use this over the original one?? I'd like to know the benefits.

Thanks!

**Comment by iceheat** [comment]
This is a fork of the amazing package developed and maintained by Jens Segers. We aim to provide faster and better support and bug fixes on this package. In addition to nicer documentation. I wouldn't consider switching package as neither an upgrade nor a downgrade.

**Comment by ebisbe** [comment]
Ok, so you will push all changes here to the other?

**Comment by pi0** [comment]
@ebisbe Sure. we are using this package (with more upstream merges) on production apps @Fandogh :) All stable changes will be periodically push here...

**Comment by ebisbe** [comment]
Thanks @pi0 ! I will switch once I have time.
