### ISSUE TITLE
queue:work is not working.

### ISSUE THREAD

**Issue by RKalkani** [moloquent/moloquent#55]
```
ErrorException: Undefined property: Moloquent\Queue\MongoQueue::$expire in ........./vendor/moloquent/moloquent/src/Queue/MongoQueue.php:23
```

Getting above exception in every try. MongoDB jobs collection has jobs but none of them are processing by queue.

**Comment by arogozin** [comment]
@RKalkani fixed in my PR. Check #59

**Comment by anhphamt** [comment]
Please review and merge this change.

**Comment by pi0** [comment]
Merged :)

**Comment by RKalkani** [comment]
@pi0 @arogozin I will test PR today and update output.

**Comment by anhphamt** [comment]
Thanks @pi0

**Comment by anhphamt** [comment]
`Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Moloquent\Queue\MongoQueue::getTime() in vendor/moloquent/moloquent/src/Queue/MongoQueue.php:62`

Undefined method getTime().

**Comment by codefun01** [comment]
How can I get these changes as I am not able to find in last release 0.4?
