### ISSUE TITLE
Password Reset Service Provider

### ISSUE THREAD

**Issue by j-ibarra** [moloquent/moloquent#65]
hello everyone, I have some problem when I try reset e password

FatalThrowableError in DatabaseTokenRepository.php line 58:
Type error: Argument 2 passed to Illuminate\Auth\Passwords\DatabaseTokenRepository::__construct() must implement interface Illuminate\Contracts\Hashing\Hasher, string given, called in /home/jcs/Documentos/docker/applaravel/vendor/moloquent/moloquent/src/Auth/PasswordBrokerManager.php on line 22

I  register this included service provider

Moloquent\MongodbServiceProvider::class,
Moloquent\Auth\PasswordResetServiceProvider::class,

I use make:auth to  Laravel's native Auth functionality

I can register, login and logout

![image](https://cloud.githubusercontent.com/assets/4218738/25921495/a0ecc400-35a3-11e7-96d6-aeec099d7e9d.png)

**Comment by dees040** [comment]
[This PR](https://github.com/jenssegers/laravel-mongodb/pull/1162) fixes that bug.
