### ISSUE TITLE
Laravel 5.5 Support

### ISSUE THREAD

**Issue by robsoncombr** [moloquent/moloquent#82]
Error with new official released Laravel 5.5

Declaration of Moloquent\Eloquent\HybridRelations::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Illuminate\Database\Eloquent\Model::belongsToMany($related, $table = NULL, $foreignPivotKey = NULL, $relatedPivotKey = NULL, $parentKey = NULL, $relatedKey = NULL, $relation = NULL)

**Comment by J-Ibarra** [comment]
please see this [pull](https://github.com/moloquent/moloquent/pull/83)

**Comment by robsoncombr** [comment]
Thank you.
