### ISSUE TITLE
Update to Laravel 5.5

### ISSUE THREAD

**Issue by j-ibarra** [moloquent/moloquent#85]
Hello everyone!

the next entry is to discuss the laravel 5.5 update

yesterday a small bug was fixed in [HybridRelations.php](https://github.com/moloquent/moloquent/commit/f5c810eacfbbf4ceca0fcc44f08d96db400af7e6)

but I think that you have to make a new branch only for version 5.4 and the dev-master for the new version that can include the new laravel features to install the dependencies that the user does not have to configure the file config/app.php (please see [this](https://laracasts.com/series/whats-new-in-laravel-5-5/episodes/5))

```
 "extra" : {
    "laravel" : {
        "providers" : [
            "Moloquent\\MongodbServiceProvider",
            "Moloquent\ \Auth\\PasswordResetServiceProvider",
            "Moloquent\\MongodbQueueServiceProvider",
            "Moloquent\\Passport\\PassportServiceProvider"
        ],
        "aliases" : {
           "Moloquent" : "Moloquent\Eloquent\Model"
        }
    }
 }
```

also I have achieved with a few bugs in the basic auth of laravel, missing the tails, the passport, and other tasks that may be involved the Moloquent

**Comment by skys215** [comment]
Seems that this project has been deprecated?

**Comment by j-ibarra** [comment]
Yes, the lasted commit is 1 year ago!
